server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : product-service
          #uri: http://localhost:8045 eureka server up so no need use
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: cart-service
          #uri: http://localhost:8050
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**


eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
